# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
stages:
  - build
  - test
  - deploy

services:
  - docker:dind

build:
  stage: build
  image: node:latest
  cache:
    paths:
    - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist/archives
    expire_in: 2 week
  tags:
  - docker

deploy:
  stage: deploy
  image: registry.gitlab.com/softwulf/webext-deploy:latest
  dependencies:
  - build
  variables:
    WEB_EXT_APP_NAME: VideoSyncer
    WEB_EXT_ARTIFACT_DIR: /builds/Softwulf/VideoSyncer/dist/archives
    WEB_EXT_CHROME_APP_ID: ofpeaemcoefdpfkimgghkkggcimkjepk
    WEB_EXT_AMO_APP_ID: "{560ece31-4892-44b1-b1cc-331bad846f57}"
    WEB_EXT_SOURCE_DIR: /builds/Softwulf/VideoSyncer
  script:
  - pwd
  - ls $(pwd)
  - npm start --prefix /webext-deploy
